# Generated by Django 5.2.8 on 2025-11-21 05:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import schoolApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('class_name', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busNumber', models.CharField(max_length=50)),
                ('driverName', models.CharField(max_length=100)),
                ('driverPhone', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('start', models.CharField(max_length=100)),
                ('startDeparture', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=100)),
                ('endArrival', models.CharField(max_length=50)),
                ('aadhaarFile', models.FileField(blank=True, null=True, upload_to=schoolApp.models.aadhaar_upload_path)),
                ('licenseFile', models.FileField(blank=True, null=True, upload_to=schoolApp.models.license_upload_path)),
                ('aadhaarNameState', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhaarDataState', models.TextField(blank=True, null=True)),
                ('licenseNameState', models.CharField(blank=True, max_length=255, null=True)),
                ('licenseDataState', models.TextField(blank=True, null=True)),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('subjects', models.JSONField(default=list)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('max_seats', models.PositiveIntegerField(default=40)),
                ('room_no', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('facilities', multiselectfield.db.fields.MultiSelectField(choices=[('blackboard', 'Blackboard'), ('whiteboard', 'Whiteboard'), ('projector', 'Projector'), ('smart_board', 'Smart Board'), ('digital_display', 'Digital Display')], default='blackboard', help_text='Type of board or teaching equipment available', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='schoolApp.book')),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('mid_term', 'Mid Term'), ('final', 'Final'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('unit_test', 'Unit Test')], max_length=20)),
                ('academic_year', models.CharField(max_length=9)),
                ('term', models.CharField(max_length=50)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('exam_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schoolApp.class')),
            ],
            options={
                'ordering': ['exam_date'],
                'unique_together': {('name', 'class_name', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='FeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1025)),
                ('subject', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='homework_files/')),
                ('assignment_type', models.CharField(choices=[('class', 'Whole Class'), ('student', 'Specific Student(s)')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Assigned_By_teacher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='Account.teacherprofile')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='schoolApp.class')),
                ('students', models.ManyToManyField(blank=True, related_name='assigned_homeworks_to', to='Account.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('student', 'Student'), ('classes', 'classes'), ('Teachers', 'Teachers')], default='students', help_text='Select who this notice is for', max_length=20)),
                ('class_name', models.CharField(blank=True, help_text='Specify class if applicable (leave empty for all classes)', max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('applicable_date', models.DateField(default=django.utils.timezone.localdate)),
                ('specific_students', models.TextField(blank=True, help_text='Comma-separated names or admission numbers if notice is for specific students', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(blank=True, default=None, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('arrivalTime', models.CharField(max_length=50)),
                ('departureTime', models.CharField(max_length=50)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='schoolApp.bus')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='uploadTimeTables/')),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=10)),
                ('remark', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='Account.studentprofile')),
                ('selected_class', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='schoolApp.class')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overall_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_grade', models.CharField(blank=True, max_length=2)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolApp.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolApp.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolApp.subject')),
            ],
            options={
                'unique_together': {('student', 'exam', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.DecimalField(decimal_places=2, help_text='Maximum marks for this subject in this exam', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('exam_time', models.TimeField(blank=True, null=True)),
                ('exam_duration', models.DurationField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='schoolApp.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolApp.subject')),
            ],
            options={
                'unique_together': {('exam', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=10)),
                ('remark', models.TextField(blank=True, null=True)),
                ('selected_class', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance_records', to='schoolApp.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='Account.teacherprofile')),
            ],
            options={
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
