# Generated by Django 5.2.5 on 2025-12-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioninquiry',
            name='class_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissioninquiry',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admissioninquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='admissioninquiry',
            name='parent_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
