# Generated by Django 5.2.5 on 2025-12-11 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
        ('schoolApp', '0002_alter_admissioninquiry_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schoolApp.bus'),
        ),
    ]
