"""
Django settings for school_bos_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9!b=@e!-=kr9bj2or$8+60f@+@d%-1v_gqcc!2ka+9644ed6pe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# Allow both localhost and 127.0.0.1 dev origins used by the frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
# Allow cookies/credentials from the frontend when needed (adds
# Access-Control-Allow-Credentials: true to responses when origin matches)
CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [

    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'Account',
    'schoolApp',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Only if you need token blacklisting
    'chat',
    'whatsapp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CORS middleware should be placed as high as possible so that it can
    # add the appropriate headers to responses (including those serving media).
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'school_bos_project.middleware.BrokenPipeLoggingMiddleware',
]

ROOT_URLCONF = 'school_bos_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_bos_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'Account.User'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

from datetime import timedelta

# Optionally, add token lifetime config:
# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
# }
ENABLE_WHATSAPP = True
WHATSAPP_PHONE_NUMBER_ID = "770274896170001"
WHATSAPP_ACCESS_TOKEN = "EAAa5YLqZCC1cBP8Rt8cf6ZC1xvBqa9izGO1nhGmdUUTuwab3apoUrNJozKWs6lHWTAvN95xiaeMn4vCEZByVDWOEFGtJOZCLElnOQEEgN5hc6uSxohP5gSfxL7QJ6BHC5GmssZCyq0L7bCxZCmIyvPvg7dtQkygmnCV5CtO0FYohVGz7lZAmTMIs8asRVdijBQfCG8ZBPMFkx6Pn"
VERIFY_TOKEN = "navonous_verify_token"
APP_SECRET = "c0214f5fd8bb74bef5a30ff5c61a8296"
# SCHOOL CONTACT / ADMIN NUMBER (WhatsApp)
SCHOOL_ADMIN_WHATSAPP = "918011051028"
# ================================
# LLM + RAG CONFIGURATION
# ================================

# Where FAISS index + doc_map.json will be stored
VECTOR_INDEX_DIR = os.path.join(BASE_DIR, "vector_index")

# Embedding model used for RAG
EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

# Local LLM model name (HuggingFace)
LOCAL_LLM_MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

# Max RAG documents to use (top-k)
RAG_TOP_K = 3

# Optional: limit LLM max tokens
LLM_MAX_TOKENS = 200

# Optional safety fallback
LLM_TIMEOUT = 60  # seconds

GROQ_API_KEY = "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"