# Generated by Django 5.2.5 on 2025-11-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('menu_state', models.CharField(default='default', max_length=100)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('last_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='school_docs/')),
                ('doc_type', models.CharField(choices=[('timetable', 'Timetable'), ('fee', 'Fee Structure'), ('notice', 'Notice / Announcement'), ('rules', 'Rules & Regulations'), ('teachers', 'Teacher List'), ('general', 'General Information')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatState',
        ),
    ]
