# Generated by Django 5.2.5 on 2025-12-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_schooldocument_delete_chatstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='awaiting_child_selection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='child_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='selected_student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
