# Generated by Django 5.2.5 on 2025-12-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_awaiting_child_selection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='current_form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='form_step',
            field=models.IntegerField(default=0),
        ),
    ]
