# Generated by Django 5.2.5 on 2025-12-10 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
        ('chat', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('appointment_with', models.CharField(choices=[('principal', 'Principal'), ('teacher', 'Teacher')], max_length=20)),
                ('reason', models.TextField()),
                ('preferred_datetime', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.studentprofile')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.teacherprofile')),
            ],
        ),
    ]
