# Generated by Django 5.2.5 on 2025-12-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='selected_class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='selected_student_for_report',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
