# Generated by Django 5.2.5 on 2025-12-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatsession_is_teacher_chatsession_selected_class_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
